### ISSUE TITLE
Куди виділяти JS спільноту?

### ISSUE THREAD

**Issue by kiskesis** [grem11n/awesome-it-communities-ua#35]
В мене є JS спільнота, але там нема розділення фронтенд чи бекенд, там і nodejs деви і фронтенд, в яку категорію їх можна винести?

**Comment by kiskesis** [comment]
Також пропоную створити розділ Блокчейну

**Comment by grem11n** [comment]
Чесно кажучи, коли я створював цей мікро-проект, у мене не було якогось чіткого плану. Тому поділ спільнот досить умовний.

Можливо, є сенс ділити за "core technologies", але тоді не дуже зрозуміло, куди виносити загальні спільноти типу про DevOps або про IT in general.

Буду вдячний порадам!

**Comment by kiskesis** [comment]
Можно зробити щось по типу напрямків/мов програмування, типу:
Languages:
- JS спільноти
- C# спільноти
- Rust спільноти 
і тд і тп

**Comment by grem11n** [comment]
На жаль, в такому випадку суміжні спеціальності трохи не вписуються в концепцію. Але дякую за пораду!
Я думаю, є сенс винести окремим пунктом спільности, що повʼязані з програмуванням і окремо спільноти навколо ІТ
