### ISSUE TITLE
Kyiv Data Science - chat doesn't exists

### ISSUE THREAD

**Issue by Allirey** [grem11n/awesome-it-communities-ua#42]
> [Kyiv Data Science](https://t.me/kyivdatascience) - Telegram - Київський чат Data scientists з періодичними офлайн-мітапами.

невірне посилання або чат не існує

**Comment by beroal** [comment]
The link was added again. "Username not found."

**Comment by grem11n** [comment]
Fixed here: https://github.com/grem11n/awesome-it-communities-ua/pull/59
